// Đây là file layout của website
// File này sẽ chứa các component chung cho tất cả các trang của website
// Ví dụ như header, footer, sidebar, ...
// Để sử dụng các component chung này, chúng ta sẽ sử dụng tag <children> trong file layout.tsx
// Các component chung này sẽ được đặt trong thẻ <children>

"use client"
import {Provider} from "react-redux"
import {store} from "../lib/store"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//import các component chung
import Header from "../components/user/layout/Header";
import Footer from "../components/user/layout/Footer";

//import font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
    <html lang="vi">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      {/* ------------------------------ */}
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <div className="bg-gray-100 font-sans min-h-screen flex flex-col">
          <header>
            <Header />
          </header>
          <nav></nav>

          {/* Nội dung của trang sẽ được render ở đây */}
          <main className="flex-grow">{children}</main>
          {/* --------------------------------------- */}

          <footer>
            <Footer />
          </footer>
        </div>
      </body>
      {/* ------------------------------ */}
    </html>
    </Provider>
  );
}
